# Generated by Django 3.1.4 on 2020-12-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceofclubs', '0002_event_eventtype_group_permission_state_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
