# Generated by Django 3.1.4 on 2020-12-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceofclubs', '0004_auto_20201203_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='status',
            new_name='state',
        ),
    ]
